// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMJt4lCLlDhJHcJN0z0yP57C239KURZ-8',
    appId: '1:964131940870:web:339f18dec5eff3aefcf187',
    messagingSenderId: '964131940870',
    projectId: 'kitahack-foodlink-627c2',
    authDomain: 'kitahack-foodlink-627c2.firebaseapp.com',
    storageBucket: 'kitahack-foodlink-627c2.firebasestorage.app',
    measurementId: 'G-MSDPG16RGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxNlNe0c-6IX4YHUkDf93dOammA6uG_d8',
    appId: '1:964131940870:android:2ec55ae6c3ba12bafcf187',
    messagingSenderId: '964131940870',
    projectId: 'kitahack-foodlink-627c2',
    storageBucket: 'kitahack-foodlink-627c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWRcNhqBIIXG4l6LUEv8aRl142-bi5_D0',
    appId: '1:964131940870:ios:6b306cba491faee5fcf187',
    messagingSenderId: '964131940870',
    projectId: 'kitahack-foodlink-627c2',
    storageBucket: 'kitahack-foodlink-627c2.firebasestorage.app',
    iosBundleId: 'com.foodLink.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWRcNhqBIIXG4l6LUEv8aRl142-bi5_D0',
    appId: '1:964131940870:ios:d9e6a11cd99d8d58fcf187',
    messagingSenderId: '964131940870',
    projectId: 'kitahack-foodlink-627c2',
    storageBucket: 'kitahack-foodlink-627c2.firebasestorage.app',
    iosBundleId: 'com.example.foodLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMJt4lCLlDhJHcJN0z0yP57C239KURZ-8',
    appId: '1:964131940870:web:c82ee12f4752bbaefcf187',
    messagingSenderId: '964131940870',
    projectId: 'kitahack-foodlink-627c2',
    authDomain: 'kitahack-foodlink-627c2.firebaseapp.com',
    storageBucket: 'kitahack-foodlink-627c2.firebasestorage.app',
    measurementId: 'G-XJR2W4K7TT',
  );
}
